package punto_de_venta;

import com.sun.glass.events.KeyEvent;
import com.sun.javafx.scene.paint.GradientUtils;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class principal extends javax.swing.JFrame {

    private String[][] productos
            = {
                {"1", "Baguette", "90"},
                {"2", "Boneless", "90"},
                {"3", "Wrap", "100"},
                {"4", "Ensalada", "130"},
                {"5", "Gyro", "90"}
            };

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setSize(WIDTH, WIDTH);
        this.jLabel1.setLocation(this.getWidth() / 4, this.getWidth() / 2);
        this.jLabel3.setText("TOTAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataGridView1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textBox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 300));
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Punto de Venta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 144, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date dateAndTime = Calendar.getInstance().getTime();
        jLabel2.setText(dateAndTime.toString());
        jLabel2.setAlignmentY(0.0F);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 60, 107, 22);

        dataGridView1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRECIO", "PRODUCTO", "CANTIDA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(dataGridView1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(66, 88, 320, 156);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 270, 140, 14);

        textBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBox1KeyPressed(evt);
            }
        });
        getContentPane().add(textBox1);
        textBox1.setBounds(20, 270, 250, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void textBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarProductos();
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
        }
        if (evt.getKeyCode() == KeyEvent.VK_T) {
        }
    }//GEN-LAST:event_textBox1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataGridView1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textBox1;
    // End of variables declaration//GEN-END:variables
    

    private void buscarProductos() {
        DefaultTableModel model = (DefaultTableModel) dataGridView1.getModel();
        Vector row = new Vector();
        String text = textBox1.getText();
        if (text.indexOf('*') != -1) {
            //JOptionPane.showMessageDialog(null, "Es mas de un articulo");
            String[] ej = text.split("\\*");
            for (int i = 0; i < 5; i++) {
                String prod = ej[1].toString();
                if (prod.equals(productos[i][0])) {
                    row.add(productos[i][2]);
                    row.add(productos[i][1]);
                    row.add(ej[0]);
                    row.add(Float.parseFloat(productos[i][2]) * Float.parseFloat(ej[0]));
                    model.insertRow(model.getRowCount(), row);
                    //precio, producto, cantidad, total de ese producto
                    total();
                }
            }
        } else {
            for (int i = 0; i < 5; i++) {
                if (textBox1.getText().equals(productos[i][0])) {
                    row.add(productos[i][2]);
                    row.add(productos[i][1]);
                    row.add("1");
                    row.add(productos[i][2]);
                    model.insertRow(model.getRowCount(), row);
                    //model.addRow(new Object[]{str1, str2, str3});
                    total();
                }
            }
        }
    }

    private void total() {
        float total = 0;
        for (int i = 0; i < dataGridView1.getRowCount(); i++) {
            total += (float) dataGridView1.getValueAt(i, 3);
        }
        jLabel3.setText("TOTAL "+total);
        this.textBox1.setText(null);
    }

}
